---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle

inputs:
  - name: git-repo
  - name: version

outputs:
  - name: artifact-dir

run:
  path: git-repo/ci/tasks/build-artifact.sh
