---
platform: linux

image_resource:
  type: docker-image
  source:
     repository: nulldriver/cf-cli-resource
     tag: latest


inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/verify-test.sh

params:
  CONCOURSE_DEMO_URL:
