jobs:
  - name: unit-tests
    plan:
    - get: git-repo
      trigger: true
    - task: unit
      file: git-repo/ci/tasks/unit.yml

  - name: build-artifact
    serial_groups: [version]
    serial: true
    plan:
    - get: git-repo
      passed: [unit-tests]
      trigger: true
    - get: version
      params: { pre: rc }
    - task: build-artifact
      file: git-repo/ci/tasks/build-artifact.yml
      timeout: 5m
    - put: release-candidate
      params:
        file: artifact-dir/rockme*.jar
    - put: git-repo
      params:
        repository: git-repo
        tag: version/number
    - put: version
      params: {file: version/number}

  - name: integration-tests
    serial_groups: [version]
    plan:
    - aggregate:
      - get: version
        passed: [build-artifact]
        trigger: true
      - get: release-candidate
        passed: [build-artifact]
      - get: git-repo
        passed: [build-artifact]
    - put: TAS-TEST-CLOUD
      params:
        manifest: git-repo/manifest-test.yml
        current_app_name: rockme-test
        path: release-candidate/rockme*.jar
   
  - name: acceptance-tests
    serial_groups: [version]
    plan:
    - aggregate:
      - get: release-candidate
        passed: [integration-tests]
        trigger: true
      - get: version
        passed: [integration-tests]
      - get: git-repo
        passed: [integration-tests]
    - put: TAS-UAT-CLOUD
      params:
        manifest: git-repo/manifest-uat.yml
        current_app_name: rockme-uat
        path: release-candidate/rockme*.jar

  - name: ship-to-production
    serial_groups: [version]
    serial: true
    plan:
    - aggregate:
      - get: release-candidate
        passed: [acceptance-tests]
      - get: version
        params: { bump: final }
        passed: [acceptance-tests]
      - get: git-repo
        passed: [acceptance-tests]
    - task: prepare-final
      file: git-repo/ci/tasks/prepare-final.yml
      params:
        base_name: rockme
    - put: TAS-PROD-CLOUD
      params:
        manifest: git-repo/manifest-prod.yml
        current_app_name: rockme
        path: final-dir/rockme*.jar

  - name: major
    serial_groups: [ version ]
    plan:
      - put: version
        params: { bump: major, pre: rc }

  - name: minor
    serial_groups: [ version ]
    plan:
      - put: version
        params: { bump: minor, pre: rc }

  - name: patch
    serial_groups: [ version ]
    plan:
      - get: version
        passed: [ ship-to-production ]
        trigger: true
      - put: version
        params: { bump: patch }

resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: master
  
- name: TAS-TEST-CLOUD
  type: cf
  source:
    api: {{TAS_TEST_API}}
    username: {{TAS_TEST_USER}}
    password: {{TAS_TEST_PASS}}
    organization: {{TAS_TEST_ORG}}
    space: {{TAS_TEST_SPACE}}
    skip_cert_check: true

- name: TAS-UAT-CLOUD
  type: cf
  source:
    api: {{TAS_UAT_API}}
    username: {{TAS_UAT_USER}}
    password: {{TAS_UAT_PASS}}
    organization: {{TAS_UAT_ORG}}
    space: {{TAS_UAT_SPACE}}
    skip_cert_check: true

- name: TAS-PROD-CLOUD
  type: cf
  source:
    api: {{TAS_PROD_API}}
    username: {{TAS_PROD_USER}}
    password: {{TAS_PROD_PASS}}
    organization: {{TAS_PROD_ORG}}
    space: {{TAS_PROD_SPACE}}
    skip_cert_check: true

- name: version
  type: semver
  source:
    bucket: {{S3_BUCKET}}
    key: {{S3_VERSION_FILE}}
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}
    initial_version: 1.0.0

- name: release-candidate
  type: s3
  source:
    bucket: {{S3_BUCKET}}
    regexp: {{S3_PIPELINE_ARTIFACTS}}
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}

